#!/bin/bash
source /home/zqzhou/disk/miniconda3/bin/activate learn
python deeplabv3plus/train.py \
--cuda True \
--gpu_id 1 \
--dataset voc2011 \
--lr 7e-3 \
--weight_decay 0 \
--fuse_attention False \
--batch_size 8 \
--arch DeepLabV3Plus \
--backbone resnet101 \
--test_imgs_dir test_imgs \
--data_dir Datasets \
--ratio 1 \
--base_size  684 \
--crop_size 513 \
--scale True \
--epochs 250 \
--optimizer SGD \
--momentum 0.9 \
--scheduler  Poly \
--min_lr 5e-6 \
--patience 5 \
--lr_gamma 0.5 \
--random_seed 1337 \
