#!/bin/bash
source /home/zqzhou/disk/miniconda3/bin/activate learn
python fcn/train.py \
--cuda True \
--gpu_id 1 \
--dataset vocaug \
--lr 1e-3 \
--weight_decay 5e-4 \
--fuse_attention False \
--batch_size 16 \
--arch FCN8s \
--test_imgs_dir test_imgs \
--data_dir Datasets \
--ratio 1 \
--base_size  354 \
--crop_size 256 \
--scale True \
--epochs 250 \
--optimizer SGD \
--momentum 0.9 \
--scheduler  Poly \
--min_lr 5e-6 \
--patience 5 \
--lr_gamma 0.5 \
--random_seed 1337 \
--resume False \
--ft False \
--checkpoint_PATH  fcn/.vocaug/200718_181005_SGD_lr_1e-03_wd_4e-04_fa_False/model.pth \
